pull request to add first spotify commands
medialab/minet pull request #721
Opened 2023-04-29 17:47 UTC by kat-kel

This is a first draft at creating a new command for minet, `spotify`, which queries Spotify's Web API.

It requires a new `"spotify"` section in the rcfile with what Spotify calls a "client_id" and "client_secret". [They're generated when you create an app for the API on a Spotify account](https://developer.spotify.com/documentation/web-api/tutorials/getting-started), which I did for testing. I can give you my testing tokens if you want. They can also be passed individually to the command as options.
```json
{"spotify": 
    {
        "client_id": "AAAA",
        "client_secret": "BBBB"
    }
}
```

The first commands I've proposed to add are [general searches](https://developer.spotify.com/documentation/web-api/reference/search) on the API of (1) podcast shows and (2) podcast episodes, based on a keyword match in the show or episode's name or description. In addition to a keyword (query), the search can take on a parameter that filters the country (`--market`) in which the podcast was distributed.

For example,
```shell
>>> minet spotify episodes "reforme retraites" --market FR --rcfile config.yml -o reforme_episodes.csv
```

One thing I don't like yet is that if you give an invalid country code to the `--market` option (i.e. `--market FRA`), the `request` function used in `minet/spotify/api_client.py` throws a `KeyError` and it's not descriptive of the problem.

2023-04-29 17:56 UTC, kat-kel commented
One particularity about Spotify's API is that an application does not have a permanent access token. Every 30 minutes, you need to request a new one. My solution was to use minet's `request` with the "POST" method, see below, to get a new access token each time the API Wrapper is instantiated:
https://github.com/medialab/minet/blob/44a9aef972a68c72d9b5c3805b121fffee1f7e0f/minet/spotify/api_client.py#L14-L34

2023-05-03 11:37 UTC, Yomguithereal requested changes

2023-05-03 11:37 UTC, Yomguithereal commented on minet/spotify/api_client.py
> +            time.sleep(30)
We should log this probably at one point. But let's discuss this later.

2023-05-03 11:37 UTC, Yomguithereal commented on minet/spotify/api_client.py
> +    def generator(self, url, formatter):
This should probably named `paginate` or something like this?

2023-05-03 11:37 UTC, Yomguithereal commented on minet/spotify/api_client.py
> +        while go_to_next_page:
`while True` with a `break` somewhere feels clearer to me.

2023-05-03 11:37 UTC, Yomguithereal commented on minet/spotify/api_client.py
> +                raise KeyError
This should be a custom error somehow.

2023-05-03 11:37 UTC, Yomguithereal commented on minet/spotify/api_client.py
> +    def generator(self, url, formatter):
Note that I would probably make this handle only the actual API pagination and yield the payload but maybe not extract the items if this is different for each kind of call.

2023-07-11 15:58 UTC, closed without merging