Dump graph
medialab/minet pull request #793
Opened 2023-06-15 14:56 UTC by 16arpi

2023-06-15 15:13 UTC, Yomguithereal commented on minet/cli/dump/dump_graph.py
> +from minet.crawl.queue import CrawlerQueue
Je ne pense pas que cet import est pertinent

2023-06-15 15:13 UTC, Yomguithereal commented on minet/cli/dump/dump_graph.py
> +    print(cli_args)
Ce print doit mourir, c'est du debug

2023-06-15 15:13 UTC, Yomguithereal commented on minet/cli/dump/dump_graph.py
> +        id = row[h.id]
Si tu déréférence `h.id` à chaque entrée de la boucle tu perds de la perf.

2023-06-15 15:13 UTC, Yomguithereal commented on minet/cli/dump/dump_graph.py
> +        degree = int(row[h.degree])
Degree tu peux oublier, parce qu'on aura cette information naturellement dans le graph.

2023-06-15 15:13 UTC, Yomguithereal commented on minet/cli/dump/dump_graph.py
> +        if edge.get("source") and edge.get("target"):
Il vaut mieux tester qu'on a un parent avant de créer les données de l'arc qu'on va jeter si on a pas besoin de s'en servir.

2023-06-15 15:18 UTC, 16arpi commented on minet/cli/dump/__init__.py
> +        a jobs csv and visual it as a network.
J'ai mis `manipulate`

2023-06-20 12:18 UTC, Yomguithereal requested changes

2023-06-20 12:18 UTC, Yomguithereal commented on minet/cli/cast.py
> +class CSVRowCaster(object):
A remettre dans cli/dump/dump_graph

2023-06-20 12:18 UTC, Yomguithereal commented on minet/cli/constants.py
> +DEFAULT_CRAWLER_CAST = {
A remettre dans cli/dump/dump_graph

2023-06-20 12:18 UTC, Yomguithereal commented on minet/cli/dump/__init__.py
> +            "flags": ["-l", "--label"],
Peut-être qu'on veut un truc par défaut pour le label par ailleurs non?

2023-06-20 12:18 UTC, Yomguithereal commented on minet/cli/dump/dump_graph.py
> +    crow = caster.cast_row(fieldnames, row)
Corbeau? Ya moyen de trouver un nom de variable plus clair :)

2023-06-20 12:18 UTC, Yomguithereal commented on minet/cli/dump/dump_graph.py
> +        id = row[fields["id"]]
Gaffe au shadowing

2023-06-20 12:18 UTC, Yomguithereal commented on minet/cli/dump/dump_graph.py
> +            "size": 20,
That's weird

2023-06-20 12:18 UTC, Yomguithereal commented on minet/cli/dump/dump_graph.py
> +            "size": 20,
Mettre le degré du node.

2023-06-20 13:13 UTC, merged